FROM python:3

WORKDIR /

COPY service-requirements.txt ./
RUN pip install --no-cache-dir -r service-requirements.txt
ENV KAFKA_SERVICE_INTERNAL_HOST ${KAFKA_SERVICE_INTERNAL_HOST}
ENV KAFKA_SERVICE_INTERNAL_PORT ${KAFKA_SERVICE_INTERNAL_PORT}
ENV KAFKA_TOPIC_SUBSCRIBE ${KAFKA_TOPIC_SUBSCRIBE}
ADD app /app
